# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-70bea1292eab439194774b32f05a7eb6
      model-name: deepseek-v4-flash-vision-exp
      strict-json-schema: true
      response-format: json_object
      log-requests: true
      log-responses: true
      #max-tokens: 8192